services:
  api:
    build: fib-api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - spring-postgres
      - spring-redis
      - spring-nginx-client
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./fib-worker
    volumes:
      - /app/node_modules
      - ./fib-worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - spring-redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./fib-client
    volumes:
      - /app/node_modules
      - ./fib-client:/app
    ports:
      - 3000:3000
    networks:
      - spring-nginx-client
  nginx:
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - 3050:80
    networks:
      - spring-nginx-client
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
  spring-redis:
  spring-nginx-client:
